spring.application.name=calendar
spring.datasource.url=jdbc:postgresql://localhost:5432/clcdb
spring.datasource.username=postgres
spring.datasource.password=QOWULafbWkXbbrehLLvVoMbjUSgzivJC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true