spring.application.name=calendar
spring.datasource.url=postgresql://postgres:mXRnxOFdjXdbNDVcWJboqMCHXeDgcsNk@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=QOWULafbWkXbbrehLLvVoMbjUSgzivJC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true