spring.application.name=calendar

# Настройка подключения к файлу БД. Путь можно указать абсолютный или относительный
spring.datasource.url=jdbc:sqlite:data/calendar.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Настройка JPA и Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.init_sql=PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL;